name: Code Quality

on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy 
        pip install -r utility_scripts/requirements.txt

    - name: Lint and Format
      run: black utility_scripts/ --check --diff

    - name: Type Checking
      run: mypy utility_scripts/

    - name: Check for Dependency Updates
      run: pip list --outdated

    - name: Check for Changes
      id: check-changes
      run: echo "::set-output name=changes::$(git diff --name-only)"

    - name: Commit and Push Changes (if needed)
      if: steps.check-changes.outputs.changes != ''
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Auto-format code and maintain code hygiene"
        git push
